name: Deploy Application on Docker

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:
    inputs:
      target_server:
        description: 'Select the server to deploy to'
        required: true
        default: 'server_1'
        type: choice
        options:
          - server_1
          - server_2
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./AspnetCoreMvcFull.csproj
      - name: Build
        run: dotnet build ./AspnetCoreMvcFull.csproj --no-restore
      - name: Publish
        run: dotnet publish ./AspnetCoreMvcFull.csproj --configuration Release --output ./publish
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:latest
      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:latest
      #       docker stop aspnetcoremvcfull || true
      #       docker rm aspnetcoremvcfull || true
      #       docker run -d --name aspnetcoremvcfull -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:latest 
      # - name: Deploy to Server via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     envs: GITHUB_SHA
      #     script: |
      #       # Navigate to your app directory
      #       cd /path/to/your/docker-compose-folder
            
      #       # Create or update an .env file so compose knows which image to use
      #       echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:${{ github.sha }}" > .env
            
      #       # Pull the specific new image
      #       docker compose pull
            
      #       # Start/Update services (only changes will be applied)
      #       docker compose up -d --remove-orphans
  deploy_server_1:
    needs: build
    if: github.event.inputs.target_server == 'server_1'
    runs-on: ubuntu-latest
    environment: Production_Server_1
    steps:
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_1_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu
            echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:${{ github.sha }}" > .env
            docker compose pull
            docker compose up -d    
    
  deploy_server_2:
    needs: build
    if: github.event.inputs.target_server == 'server_2'
    runs-on: ubuntu-latest
    environment: Production_Server_2
    steps:
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_2_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu
            echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/aspnetcoremvcfull:${{ github.sha }}" > .env
            docker compose pull
            docker compose up -d          